package com.one.ForoHub.models.topic;

public enum Course {
         INTRODUCTION_TO_INFORMATION_TECHNOLOGY,
         FUNDAMENTALS_OF_PROGRAMMING_WITH_JAVA,
         WEB_DEVELOPMENT_ESSENTIALS,
         DATABASE_MANAGEMENT_SYSTEMS,
         NETWORK_SECURITY_AND_CRYPTOGRAPHY,
         DATA_STRUCTURES_AND_ALGORITHMS,
         SOFTWARE_ENGINEERING_PRINCIPLES,
         CLOUD_COMPUTING_AND_VIRTUALIZATION,
         MOBILE_APP_DEVELOPMENT_WITH_ANDROID,
         BIG_DATA_ANALYTICS_AND_MACHINE_LEARNING
}
